In [2]:
import pandas as pd
import numpy as np

In [22]:
a = np.random.randint(10, size=10)

In [23]:
a

array([3, 6, 4, 0, 5, 7, 4, 0, 8, 6])

In [24]:
np.mean(a)

4.3

In [25]:
np.std(a)

2.570992026436488

In [26]:
b=np.random.rand(10)

In [27]:
b

array([0.88395141, 0.72858023, 0.57655066, 0.81377606, 0.00431878,
       0.55003108, 0.49088104, 0.11692583, 0.42890639, 0.5982019 ])

In [28]:
np.mean(b)

0.5192123397191217

In [29]:
np.std(b)

0.26646233413117093

In [30]:
np.sum(a)

43

In [32]:
np.mean(a)/len(a)

0.43

In [33]:
a

array([3, 6, 4, 0, 5, 7, 4, 0, 8, 6])

In [39]:
v_a=np.sum((a-np.mean(a))**2)/len(a)
v_a

6.609999999999999

In [40]:
np.sqrt(v_a)

2.570992026436488